### ISSUE TITLE
Handle enter key when navigating suggestions

### ISSUE THREAD

**Issue by doei** [vakhtang/react-search-bar#2]
Hey, thanks for the simple and super usable component.
I wanted to add return key support when navigating the suggestions with the arrows, so my quick hack was to change a couple lines, namely:

``` javascript
//starting line 6
const KEY_CODES = {
  up: 38,
  down: 40,
  enter: 13 // << added
};
//...starting line 67
    if (e.which == KEY_CODES.up) {
      item = (item <= 0) ? lastItem : item - 1;
    } else if (e.which == KEY_CODES.enter) { //<< added
      this.search(suggestions[item])         //<<
    } else {
      item = (item == lastItem) ? 0 : item + 1;
    }
//... starting line 107
onKeyDown={(e) => {
              (e.which == KEY_CODES.up || e.which == KEY_CODES.down || e.which == KEY_CODES.enter) &&
              this.state.suggestions &&                                     //^^ added
              this.onKeyDown(e);
            }}
```

sorry i'm not PRing this, npm 3.3.6 is giving me trouble and I really did this not thinking too much if it was actually the right way to handle that, but hey, works for me...

Cheers

**Comment by vakhtang** [comment]
This is due to a bug. I'll have a fix in shortly. For now, you can supply an empty callback to the `onSubmit` prop to get this working.

**Comment by doei** [comment]
I'm not sure I understand how an empty callback would get the enter key working (was that what you meant anyway?). My quickfix is working for me right now.

**Comment by vakhtang** [comment]
That is what I meant. The presence of the submit button obviates the need for explicitly handling the user hitting enter (I will be refactoring this to accommodate no submit button). The bug was occurring because the `onSubmit` method on the component--which gets called when the user hits enter and thus does a submit--wasn't being called unless the `onSubmit` prop was set. I've since [fixed this](https://github.com/vakhtang/react-search-bar/commit/beb125fdd16460f822b6d0e3718bbfa4f8f29b5a), and I'll be pushing a new release soon. My stopgap solution prevents you from having to modify the component directly.

How are handling the search without a callback anyway? Assuming the interaction uses AJAX and isn't a regular form submit (which is what you want from the sound of it), you have to pass a handler to `onSubmit` to do something with the result.

**Comment by doei** [comment]
In my case suggestions are loaded prior, so no AJAX within SearchBar use. I do indeed use `onSubmit` to retrieve the value of the chosen suggestion, in my modification I call the search function in the switch statement for the `KEY_CODE.enter` case, which in turn calls `onSubmit`...

**Comment by vakhtang** [comment]
I think the issue is that in my demo, the component is wrapped in a form, which is what allows the enter => submit action to work. Are you by any chance not wrapping the component with a form?

**Comment by doei** [comment]
ah right ! I'm indeed not doing that, maybe I should..

**Comment by vakhtang** [comment]
Actually, this is something I need to fix. You don't **need** to wrap it in a form element, so you're fine. I'll have a fix in shortly. Sorry about that. :)

**Comment by doei** [comment]
Sure, but it's still a simpler solution than mine..
Cheers
